<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Constant\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EduApoyosDomain\EduApoyosDomain.csproj" />
  </ItemGroup>

</Project>
